name: ga_dz5


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Debug

jobs:
  work:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
       submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y cmake lcov libgtest-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
  
    - name: Run tests
      run: |
        cd build/tests && ctest --output-on-failure && ${{github.workspace}}/build/tests/test

    - name: Coverage
      run: |
        lcov --directory . --capture --output-file coverage.info --ignore-errors mismatch
        lcov --remove coverage.info '*/gtest/*' '/usr/*' --output-file coverage.info
        genhtml coverage.info --output-directory coverage_report --ignore-errors mismatch

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        path-to-lcov: ${{github.workspace}}/coverage.info
        github-token: ${{ secrets.GITHUB_TOKEN }}
